package com.myself.app.model.retrofit.entity;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * auto greenDao generate javaBean by lsc
 */
@Entity(nameInDb = "TestBean")
public class TestBean implements Comparable<TestBean> {

    @Id
    private Long id;
    private String userId;
    private String searchString;
    private String searchUrl;
    private String searchType;//搜索类型

    @Generated(hash = 2087637710)
    public TestBean() {
    }

    public TestBean(Long id) {
        this.id = id;
    }

    @Generated(hash = 1889714242)
    public TestBean(Long id, String userId, String searchString, String searchUrl, String searchType) {
        this.id = id;
        this.userId = userId;
        this.searchString = searchString;
        this.searchUrl = searchUrl;
        this.searchType = searchType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getSearchString() {
        return searchString;
    }

    public void setSearchString(String searchString) {
        this.searchString = searchString;
    }

    public String getSearchUrl() {
        return searchUrl;
    }

    public void setSearchUrl(String searchUrl) {
        this.searchUrl = searchUrl;
    }

    public String getSearchType() {
        return searchType;
    }

    public void setSearchType(String searchType) {
        this.searchType = searchType;
    }

	@Override
	public int compareTo(TestBean old) {
		// TODO Auto-generated method stub
		return (int) (  old.getId()-id);
	}

}
