package com.myself.rxretrofitlib.utils.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.myself.rxretrofitlib.download.DownInfo;
import com.myself.rxretrofitlib.http.cookie.CookieResult;

import com.myself.rxretrofitlib.utils.dao.DownInfoDao;
import com.myself.rxretrofitlib.utils.dao.CookieResultDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downInfoDaoConfig;
    private final DaoConfig cookieResultDaoConfig;

    private final DownInfoDao downInfoDao;
    private final CookieResultDao cookieResultDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downInfoDaoConfig = daoConfigMap.get(DownInfoDao.class).clone();
        downInfoDaoConfig.initIdentityScope(type);

        cookieResultDaoConfig = daoConfigMap.get(CookieResultDao.class).clone();
        cookieResultDaoConfig.initIdentityScope(type);

        downInfoDao = new DownInfoDao(downInfoDaoConfig, this);
        cookieResultDao = new CookieResultDao(cookieResultDaoConfig, this);

        registerDao(DownInfo.class, downInfoDao);
        registerDao(CookieResult.class, cookieResultDao);
    }
    
    public void clear() {
        downInfoDaoConfig.clearIdentityScope();
        cookieResultDaoConfig.clearIdentityScope();
    }

    public DownInfoDao getDownInfoDao() {
        return downInfoDao;
    }

    public CookieResultDao getCookieResultDao() {
        return cookieResultDao;
    }

}
